// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const sanitizeEnv = (value: string | undefined) =>
  value
    ?.trim()
    // Handle accidental quoting from env providers
    .replace(/^"|"$/g, '')
    .replace(/^'|'$/g, '')
    // Handle accidental literal "\n" plus real newlines
    .replace(/\\n/g, '')
    .replace(/[\r\n]/g, '')
    .trim();

const SUPABASE_URL = sanitizeEnv(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = sanitizeEnv(import.meta.env.VITE_SUPABASE_ANON_KEY);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '⚠️ Supabase environment variables are missing.\n' +
    'Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your .env file.\n' +
    'See .env.example for reference.'
  );
}

export { SUPABASE_PUBLISHABLE_KEY };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// SQL statements
/*
insert into storage.buckets (id, name, public)
values ('email-assets', 'email-assets', false)
on conflict (id) do update set name = excluded.name, public = false;

drop policy if exists "Service role can manage email assets" on storage.objects;
create policy "Service role can manage email assets"
on storage.objects
for all
to service_role
using (bucket_id = 'email-assets');
*/